### ISSUE TITLE
Fix local precommit to format code

### ISSUE THREAD

**Issue by veekaybee** [mozilla-ai/lumigator#213]
**Describe the bug**
Right now, we run local linting via precommit optionally. Because we need to custom-configure Pants, we need to use a `local` repo, which is not ideal from precommit's perspective, and this precommit ends up being flaky. 

https://github.com/mozilla-ai/lumigator/blob/main/.pre-commit-config.yaml

```
  - repo: local
    hooks:
      - id: pants-fmt-lint
        name: pants fmt lint
        always_run: true
        description: runs ./pants fmt on all files changed since origin/main
        entry: "pants --changed-since=origin/main fmt lint"
        language: system
        pass_filenames: false
        types: [file]
```

**System Information (please complete the following information):**

**To Reproduce**
1. Change some code
2. It should be malformatted
3. Enable precommit
4. It should still let you push to a remote branch 

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Additional context**
