### ISSUE TITLE
Evaluate DeepSeek V3 with Lumigator

### ISSUE THREAD

**Issue by ividal** [mozilla-ai/lumigator#777]
### Motivation

As part of quick evaluations, we need to evaluate the DeepSeek family of models for summarization. It would be good to see how it performs against currently supported models.

- Input data: `dialogsum` (or `thunderbird` if possible). See https://github.com/mozilla-ai/lumigator-datasets
- Metrics: `rouge`, `meteor`, `bertscore`.
- Model: DeepSeek V3 (671B). Any of the smaller models could provide a second reference, but the ask is about the full-precision DeepSeek model.
- How:
  - Invoke their [API](https://platform.deepseek.com/)
  - Invoke [Github's](https://docs.github.com/en/github-models/prototyping-with-ai-models#experimenting-with-ai-models-using-the-api) models API.

Scope: this work is separate from serving all models with HF (#729). Here we'd be using just the API (hopefully - alternatively, on-premise with vLLM). Also, consider #552 .

### Alternatives

* Serve DeepSeek on-prem using Ray and vLLM. 
* Serve quantized variants using [ollama](https://ollama.com/) or [llama.cpp](https://github.com/ggerganov/llama.cpp)

### Contribution

Consider if #552 might help.

### Have you searched for similar issues before submitting this one?

- [x] Yes, I have searched for similar issues

**Comment by dpoulopoulos** [comment]
The DeepSeek API platform has been down for at least a week. Thus, we should try deploying the model on-prem as a parallel effort.

![Image](https://github.com/user-attachments/assets/cc86e6cb-eda9-4f54-a0f0-917dfa170cfc)

**Comment by dpoulopoulos** [comment]
Let's deploy DeepSeek on-prem. This is the procedure I followed:

- Create a PVC to download the model to:
   ```yaml
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: models
  spec:
    storageClassName: shared-vast
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 4096Gi
   ```
- Create a pod and mount the PVC:
  ```yaml
  apiVersion: v1
  kind: Pod
  metadata:
    name: hf-downloader
  spec:
    containers:
      - name: hf-downloader
        image: huggingface/transformers-pytorch-gpu:latest
        command: [ "sleep", "50000" ]
        volumeMounts:
          - mountPath: /mnt/models
            name: models
        env:
          - name: HF_HOME
            value: /mnt/models
    volumes:
      - name: models
        persistentVolumeClaim:
          claimName: models
  ```
- Exec into the pod and navigate to the models dir:
  ```bash
  kubectl exec -it hf-downloader -- /bin/bash
  cd /mnt/models
  ```
- Git clone the model (this step will take a few hours) - WARNING: Change the model (see next comment on this issue):
  ```bash
  apt install git-lfs
  git lfs install
  git clone https://huggingface.co/deepseek-ai/DeepSeek-V3
  ```
- Apply the following Ray Service:
  ```yaml
  apiVersion: ray.io/v1
  kind: RayService
  metadata:
    name: deepseek-v3
  spec:
    serveConfigV2: |
      applications:
      - name: deepseek-v3
        route_prefix: /
        import_path:  lumigator.jobs.vllm.serve:model
        deployments:
        - name: VLLMDeployment
          num_replicas: 4
          ray_actor_options:
            num_cpus: 8
            # NOTE: `num_gpus` is set automatically based on TENSOR_PARALLELISM
        runtime_env:
          working_dir: "https://github.com/mozilla-ai/lumigator/archive/refs/heads/777-evaluate-deepseek.zip"
          pip: ["vllm"]
          env_vars:
            MODEL_ID: "/mnt/models/DeepSeek-V3"
            TENSOR_PARALLELISM: "8"
            PIPELINE_PARALLELISM: "4"
    rayClusterConfig:
      headGroupSpec:
        rayStartParams:
          dashboard-host: "0.0.0.0"
          object-store-memory: "2000000000"
        template:
          spec:
            containers:
            - name: ray-head
              image: rayproject/ray:2.41.0-py311-gpu
              resources:
                limits:
                  cpu: "80"
                  memory: "1000Gi"
                  nvidia.com/gpu: "8"
                requests:
                  cpu: "80"
                  memory: "1000Gi"
                  nvidia.com/gpu: "8"
              volumeMounts:
                - mountPath: /mnt/models
                  name: models
              ports:
              - containerPort: 6379
                name: gcs-server
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
              - containerPort: 8000
                name: serve
            volumes:
                - name: models
                  persistentVolumeClaim:
                    claimName: models
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: gpu.nvidia.com/class
                      operator: In
                      values:
                        - A100_NVLINK_80GB
                    - key: topology.kubernetes.io/region
                      operator: In
                      values:
                        - US-EAST-04
      workerGroupSpecs:
      - groupName: gpu-group
        replicas: 3
        rayStartParams:
          dashboard-host: "0.0.0.0"
          object-store-memory: "2000000000"
        template:
          spec:
            containers:
            - name: ray-worker
              image: rayproject/ray:2.41.0-py311-gpu
              resources:
                limits:
                  cpu: "80"
                  memory: "1000Gi"
                  nvidia.com/gpu: "8"
                requests:
                  cpu: "80"
                  memory: "1000Gi"
                  nvidia.com/gpu: "8"
              volumeMounts:
                - mountPath: /mnt/models
                  name: models
            volumes:
                - name: models
                  persistentVolumeClaim:
                    claimName: models
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: gpu.nvidia.com/class
                      operator: In
                      values:
                        - A100_NVLINK_80GB
                    - key: topology.kubernetes.io/region
                      operator: In
                      values:
                        - US-EAST-04
  ```

This should create a Ray cluster and deploy the defined application. However, this doesn't work. We should investigate why.

**Comment by dpoulopoulos** [comment]
The model is natively trained in FP8. Our on-prem cluster's A100s are not supported because of this (see https://github.com/vllm-project/vllm/issues/11539#issuecomment-2566596112). On the official [repo](https://github.com/deepseek-ai/DeepSeek-V3/tree/main) they provide a [script](https://github.com/deepseek-ai/DeepSeek-V3/blob/b5d872ead062c94b852d75ce41ae0b10fcfa1c86/inference/fp8_cast_bf16.py) to cast FP8 to BF16 and someone has already done this: https://huggingface.co/opensourcerelease/DeepSeek-V3-bf16/tree/main

We should continue with this model instead, at least temporarily. Keep in mind that this is not exactly the same model they provide through their API.

**Comment by dpoulopoulos** [comment]
This is the way we made it work (assuming that we have the model downloaded in a PVC):

- Create a Ray cluster:
  ```yaml
  apiVersion: ray.io/v1
  kind: RayCluster
  metadata:
    name: deepseek-v3-cluster
  spec:
    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
        # By default Ray allocates 30% of available memory to object storage,
        # which leads to OOM issues for jobs.
        # Set it to a proportionally lower number.
        object-store-memory: "2000000000"  # 2GB
      template:
        metadata:
          labels: {}
        spec:
          containers:
            - name: ray-head
              image: rayproject/ray:latest-py311-gpu
              ports:
                - containerPort: 6379
                  name: gcs
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
              volumeMounts:
                - mountPath: /tmp/ray
                  name: ray-logs
                - mountPath: /tmp/models
                  name: models
              # It is better to use a few large Ray pod than many small ones.
              # For production, it is ideal to size each Ray pod to take up the
              # entire Kubernetes node on which it is scheduled.
              resources:
                limits:
                  cpu: "80"
                  memory: "1000G"
                  nvidia.com/gpu: "8"
                requests:
                  cpu: "80"
                  memory: "1000G"
          # The affinity section ensures that the head pod is scheduled on a node
          # with GPUs that have at least 80GB of memory.
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: topology.kubernetes.io/region
                        operator: In
                        values:
                          - US-EAST-04
                      - key: gpu.nvidia.com/class
                        operator: In
                        values:
                          - A100_NVLINK_80GB
          volumes:
            - name: ray-logs
              emptyDir: {}
            - name: models
              persistentVolumeClaim:
                claimName: models
    workerGroupSpecs:
      - groupName: default
        rayStartParams:
          dashboard-host: "0.0.0.0"
          object-store-memory: "2000000000"
        replicas: 3
        template:
          metadata:
            labels: {}
          spec:
            containers:
              - name: ray-worker
                image: rayproject/ray:latest-py311-gpu
                ports:
                  - containerPort: 6379
                    name: gcs
                volumeMounts:
                  - mountPath: /tmp/ray
                    name: ray-logs
                  - mountPath: /mnt/models
                    name: models
                resources:
                  limits:
                    cpu: "80"
                    memory: "1000G"
                    nvidia.com/gpu: "8"
                  requests:
                    cpu: "80"
                    memory: "1000G"
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: topology.kubernetes.io/region
                          operator: In
                          values:
                            - US-EAST-04
                        - key: gpu.nvidia.com/class
                          operator: In
                          values:
                            - A100_NVLINK_80GB
            volumes:
              - name: ray-logs
                emptyDir: {}
              - name: models
                persistentVolumeClaim:
                  claimName: models
  ```
- Exec into every node and `pip install vllm`. We could avoid this step by create custom Ray images.
- Exec into the head node, and run the following command:
  ```bash
  vllm serve "/mnt/models/DeepSeek-V3-bf16" --trust-remote-code --tensor-parallel-size 8 --pipeline-parallel-size 4 --dtype bfloat16 --gpu_memory_utilization=0.8
  ```
