### ISSUE TITLE
Match the models.yaml fields with the current job creation API config

### ISSUE THREAD

**Issue by javiermtorres** [mozilla-ai/lumigator#920]
Currently, the `models.yaml` file supplied in the `/models` endpoint has a `uri` field that is related to the model config in the job creation API, but has a different format. This issue proposes to change the content of `models.yaml` slightly, as follows, from:

```yaml
- name: gpt-4o-mini
  uri: oai://gpt-4o-mini
  website_url: https://platform.openai.com/docs/models#gpt-4o-mini
  description: OpenAI's GPT-4o-mini model.
```

to:

```yaml
- name: gpt-4o-mini
  job_config:
    # may be subject to change
    model: gpt-4o-mini
    model_url: oai://gpt-4o-mini
  website_url: https://platform.openai.com/docs/models#gpt-4o-mini
  description: OpenAI's GPT-4o-mini model.
```

So the `job_config` field can be merged directly with the `job_config` field in the job create API payload.
